# Generated by Django 3.1.6 on 2021-04-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='personal_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='inputdata.personal'),
        ),
    ]
