# Generated by Django 3.1.6 on 2021-04-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inputdata', '0004_auto_20210402_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthpoints',
            name='guard_id',
        ),
        migrations.RemoveField(
            model_name='monthpoints',
            name='license',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='admin', max_length=60),
        ),
        migrations.CreateModel(
            name='MonthHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(max_length=10)),
                ('passive_working_days', models.CharField(max_length=10)),
                ('passive_working_days_hours', models.CharField(max_length=10)),
                ('passive_not_working_days', models.CharField(max_length=10)),
                ('passive_not_working_days_hours', models.CharField(max_length=10)),
                ('passive_total_hours', models.CharField(max_length=20)),
                ('active_working_days', models.CharField(max_length=10)),
                ('active_working_days_hours', models.CharField(max_length=10)),
                ('active_not_working_days', models.CharField(max_length=10)),
                ('active_not_working_days_hours', models.CharField(max_length=10)),
                ('active_total_hours', models.CharField(max_length=20)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('personal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inputdata.personal')),
            ],
            options={
                'verbose_name': 'Planilla hora extra',
                'verbose_name_plural': 'Planillas horas extras',
            },
        ),
    ]
